
NTGuide.ContentPages = {

    -- Just a starter page
    MainPage = {
        id = "main_page", 
        title = NTGuide.Localize("ntg.title.main_page"), 
        description = NTGuide.Localize("ntg.description.main_page"),
        gotoindex = {NTGuide.Localize("ntg.gotoindex.main_page")},
        features = {NTGuide.Localize("ntg.features.main_page")},
        availableaddons = {NTGuide.Localize("ntg.availableaddons.main_page")},
    },

    SettingsPage = {
        id = "settings_page", 
        title = NTGuide.Localize("ntg.title.settings_page"), 
        settings = true
    },

    -- Symptom Afflictions
    Symptoms = {
        VomitingBlood = {
            id = "vomiting_blood", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.vomiting_blood"), 
            description = NTGuide.Localize("ntg.description.vomiting_blood"), 
            causes = {NTGuide.Localize("ntg.causes.vomiting_blood")},
            treatments = {NTGuide.Localize("ntg.treatments.vomiting_blood")},
        },
        PaleSkin = {
            id = "pale_skin", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.pale_skin"), 
            description = NTGuide.Localize("ntg.description.pale_skin"), 
            causes = {NTGuide.Localize("ntg.causes.pale_skin")},
            treatments = {NTGuide.Localize("ntg.treatments.pale_skin")},
        },
        ShortnessOfBreath = {
            id = "shortness_of_breath", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.shortness_of_breath"), 
            description = NTGuide.Localize("ntg.description.shortness_of_breath"), 
            causes = {NTGuide.Localize("ntg.causes.shortness_of_breath")},
            treatments = {NTGuide.Localize("ntg.treatments.shortness_of_breath")},
        },
        Cough = {
            id = "cough", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.cough"), 
            description = NTGuide.Localize("ntg.description.cough"), 
            causes = {NTGuide.Localize("ntg.causes.cough")},
            treatments = {NTGuide.Localize("ntg.treatments.cough")},
        },
        Nausea = {
            id = "nausea", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.nausea"), 
            description = NTGuide.Localize("ntg.description.nausea"), 
            causes = {NTGuide.Localize("ntg.causes.nausea")},
            effects = {NTGuide.Localize("ntg.effects.nausea")},
            treatments = {NTGuide.Localize("ntg.treatments.nausea")},
        },
        IncreasedHeartrate = {
            id = "increased_heartrate", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.increased_heartrate"), 
            description = NTGuide.Localize("ntg.description.increased_heartrate"), 
            causes = {NTGuide.Localize("ntg.causes.increased_heartrate")},
            treatments = {NTGuide.Localize("ntg.treatments.increased_heartrate")},
        },
        Confusion = {
            id = "confusion", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.confusion"), 
            description = NTGuide.Localize("ntg.description.confusion"), 
            causes = {NTGuide.Localize("ntg.causes.confusion")},
            treatments = {NTGuide.Localize("ntg.treatments.confusion")},
        },
        Lightheadedness = {
            id = "lightheadedness", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.lightheadedness"), 
            description = NTGuide.Localize("ntg.description.lightheadedness"), 
            causes = {NTGuide.Localize("ntg.causes.lightheadedness")},
            treatments = {NTGuide.Localize("ntg.treatments.lightheadedness")},
        },
        BlurredVision = {
            id = "blurred_vision", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.blurred_vision"), 
            description = NTGuide.Localize("ntg.description.blurred_vision"), 
            causes = {NTGuide.Localize("ntg.causes.blurred_vision")},
            effects = {NTGuide.Localize("ntg.effects.blurred_vision")},
            treatments = {NTGuide.Localize("ntg.treatments.blurred_vision")},
        },
        LegSwelling = {
            id = "leg_swelling", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.leg_swelling"), 
            description = NTGuide.Localize("ntg.description.leg_swelling"), 
            causes = {NTGuide.Localize("ntg.causes.leg_swelling")},
            treatments = {NTGuide.Localize("ntg.treatments.leg_swelling")},
        },
        Wheezing = {
            id = "wheezing", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.wheezing"), 
            description = NTGuide.Localize("ntg.description.wheezing"), 
            causes = {NTGuide.Localize("ntg.causes.wheezing")},
            treatments = {NTGuide.Localize("ntg.treatments.wheezing")},
        },
        Weakness = {
            id = "weakness", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.weakness"), 
            description = NTGuide.Localize("ntg.description.weakness"), 
            causes = {NTGuide.Localize("ntg.causes.weakness")},
            effects = {NTGuide.Localize("ntg.effects.weakness")},
            treatments = {NTGuide.Localize("ntg.treatments.weakness")},
        },
        Fever = {
            id = "fever", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.fever"), 
            description = NTGuide.Localize("ntg.description.fever"), 
            causes = {NTGuide.Localize("ntg.causes.fever")},
            treatments = {NTGuide.Localize("ntg.treatments.fever")},
        },
        Sweating = {
            id = "sweating", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.sweating"), 
            description = NTGuide.Localize("ntg.description.sweating"), 
            causes = {NTGuide.Localize("ntg.causes.sweating")},
            treatments = {NTGuide.Localize("ntg.treatments.sweating")},
        },
        Bloating = {
            id = "bloating", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.bloating"), 
            description = NTGuide.Localize("ntg.description.bloating"), 
            causes = {NTGuide.Localize("ntg.causes.bloating")},
            treatments = {NTGuide.Localize("ntg.treatments.bloating")},
        },
        Inflammation = {
            id = "inflammation", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.inflammation"), 
            description = NTGuide.Localize("ntg.description.inflammation"), 
            causes = {NTGuide.Localize("ntg.causes.inflammation")},
            treatments = {NTGuide.Localize("ntg.treatments.inflammation")},
        },
        Jaundice = {
            id = "jaundice", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.jaundice"), 
            description = NTGuide.Localize("ntg.description.jaundice"), 
            causes = {NTGuide.Localize("ntg.causes.jaundice")},
            treatments = {NTGuide.Localize("ntg.treatments.jaundice")},
        },
        AbdominalDiscomfort = {
            id = "abdominal_discomfort", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.abdominal_discomfort"), 
            description = NTGuide.Localize("ntg.description.abdominal_discomfort"), 
            causes = {NTGuide.Localize("ntg.causes.abdominal_discomfort")},
            treatments = {NTGuide.Localize("ntg.treatments.abdominal_discomfort")},
        },
        Headache = {
            id = "headache", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.headache"), 
            description = NTGuide.Localize("ntg.description.headache"), 
            causes = {NTGuide.Localize("ntg.causes.headache")},
            treatments = {NTGuide.Localize("ntg.treatments.headache")},
        },
        Craving = {
            id = "craving", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.craving"), 
            description = NTGuide.Localize("ntg.description.craving"), 
            causes = {NTGuide.Localize("ntg.causes.craving")},
            treatments = {NTGuide.Localize("ntg.treatments.craving")},
        },
        Palpitations = {
            id = "palpitations", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.palpitations"), 
            description = NTGuide.Localize("ntg.description.palpitations"), 
            causes = {NTGuide.Localize("ntg.causes.palpitations")},
            treatments = {NTGuide.Localize("ntg.treatments.palpitations")},
        },
        Spasms = {
            id = "spasms", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.spasms"), 
            description = NTGuide.Localize("ntg.description.spasms"), 
            causes = {NTGuide.Localize("ntg.causes.spasms")},
            effects = {NTGuide.Localize("ntg.effects.spasms")},
            treatments = {NTGuide.Localize("ntg.treatments.spasms")},
        },
        AbdominalPain = {
            id = "abdominal_pain", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.abdominal_pain"), 
            description = NTGuide.Localize("ntg.description.abdominal_pain"), 
            causes = {NTGuide.Localize("ntg.causes.abdominal_pain")},
            effects = {NTGuide.Localize("ntg.effects.abdominal_pain")},
            treatments = {NTGuide.Localize("ntg.treatments.abdominal_pain")},
        },
        ChestPain = {
            id = "chest_pain", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.chest_pain"), 
            description = NTGuide.Localize("ntg.description.chest_pain"), 
            causes = {NTGuide.Localize("ntg.causes.chest_pain")},
            effects = {NTGuide.Localize("ntg.effects.chest_pain")},
            treatments = {NTGuide.Localize("ntg.treatments.chest_pain")},
        },
        IntensePain = {
            id = "intense_pain", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.intense_pain"), 
            description = NTGuide.Localize("ntg.description.intense_pain"), 
            causes = {NTGuide.Localize("ntg.causes.intense_pain")},
            effects = {NTGuide.Localize("ntg.effects.intense_pain")},
            treatments = {NTGuide.Localize("ntg.treatments.intense_pain")},
        },
        Vomiting = {
            id = "vomiting", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.vomiting"), 
            description = NTGuide.Localize("ntg.description.vomiting"), 
            causes = {NTGuide.Localize("ntg.causes.vomiting")},
            effects = {NTGuide.Localize("ntg.effects.vomiting")},
            treatments = {NTGuide.Localize("ntg.treatments.vomiting")},
        },
    },

    -- Head or Brain Afflictions
    Afflictions_HeadORBrain = {
        Neurotrauma = {
            id = "neurotrauma", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.neurotrauma"), 
            description = NTGuide.Localize("ntg.description.neurotrauma"), 
            causes = {NTGuide.Localize("ntg.causes.neurotrauma")},
            effects = {NTGuide.Localize("ntg.effects.neurotrauma")},
            treatments = {NTGuide.Localize("ntg.treatments.neurotrauma")},  
        },
        Stroke = {
            id = "stroke", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.stroke"), 
            description = NTGuide.Localize("ntg.description.stroke"), 
            causes = {NTGuide.Localize("ntg.causes.stroke")},
            effects = {NTGuide.Localize("ntg.effects.stroke")},
            treatments = {NTGuide.Localize("ntg.treatments.stroke")},  
        },
        Withdrawal = {
            id = "withdrawal", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.withdrawal"), 
            description = NTGuide.Localize("ntg.description.withdrawal"), 
            causes = {NTGuide.Localize("ntg.causes.withdrawal")},
            effects_withdrawal_ex1 = {NTGuide.Localize("ntg.effects.generalwithdrawal")},
            effects_withdrawal_ex2 = {NTGuide.Localize("ntg.effects.alcoholwithdrawal")},
            treatments = {NTGuide.Localize("ntg.treatments.withdrawal")},  
        },
        OpiateOverdose = {
            id = "opiate_overdose", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.opiate_overdose"), 
            description = NTGuide.Localize("ntg.description.opiate_overdose"), 
            causes = {NTGuide.Localize("ntg.causes.opiate_overdose")},
            effects = {NTGuide.Localize("ntg.effects.opiate_overdose")},
            treatments = {NTGuide.Localize("ntg.treatments.opiate_overdose")},  
        },
        Seizure = {
            id = "seizure", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.seizure"), 
            description = NTGuide.Localize("ntg.description.seizure"), 
            causes = {NTGuide.Localize("ntg.causes.seizure")},
            effects = {NTGuide.Localize("ntg.effects.seizure")},
            treatments = {NTGuide.Localize("ntg.treatments.seizure")},  
        },
        Unconsciousness = {
            id = "unconsciousness", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.unconsciousness"), 
            description = NTGuide.Localize("ntg.description.unconsciousness"), 
            causes = {NTGuide.Localize("ntg.causes.unconsciousness")},
            effects = {NTGuide.Localize("ntg.effects.unconsciousness")},
            treatments = {NTGuide.Localize("ntg.treatments.unconsciousness")},  
        },
        Coma = {
            id = "coma", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.coma"), 
            description = NTGuide.Localize("ntg.description.coma"), 
            causes = {NTGuide.Localize("ntg.causes.neurotrauma")},
            effects = {NTGuide.Localize("ntg.effects.neurotrauma")},
            treatments = {NTGuide.Localize("ntg.treatments.neurotrauma")},  
        },
        SpinalCordInjury = {
            id = "spinal_cord_injury", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.spinal_cord_injury"), 
            description = NTGuide.Localize("ntg.description.spinal_cord_injury"), 
            causes = {NTGuide.Localize("ntg.causes.spinal_cord_injury")},
            effects = {NTGuide.Localize("ntg.effects.spinal_cord_injury")},
            treatments = {NTGuide.Localize("ntg.treatments.spinal_cord_injury")},  
        },
        Concussion = {
            id = "concussion", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.concussion"), 
            description = NTGuide.Localize("ntg.description.concussion"), 
            causes = {NTGuide.Localize("ntg.causes.concussion")},
            effects = {NTGuide.Localize("ntg.effects.concussion")},
            prevention = {NTGuide.Localize("ntg.prevention.concussion")},
            treatments = {NTGuide.Localize("ntg.treatments.concussion")},  
        },
        Drunk = {
            id = "drunk", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.drunk"), 
            description = NTGuide.Localize("ntg.description.drunk"), 
            causes = {NTGuide.Localize("ntg.causes.drunk")},
            effects = {NTGuide.Localize("ntg.effects.drunk")},
            treatments = {NTGuide.Localize("ntg.treatments.drunk")},  
        },
    },

    -- Lung Afflictions
    Afflictions_Lungs = {
        RespiratoryArrest = {
            id = "respiratory_arrest", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.respiratory_arrest"), 
            description = NTGuide.Localize("ntg.description.respiratory_arrest"), 
            causes = {NTGuide.Localize("ntg.causes.respiratory_arrest")},
            effects = {NTGuide.Localize("ntg.effects.respiratory_arrest")},
            treatments = {NTGuide.Localize("ntg.treatments.respiratory_arrest")},
            firstaid = {NTGuide.Localize("ntg.firstaid.respiratory_arrest")},    
        },
        LungDamage = {
            id = "lung_damage", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.lung_damage"), 
            description = NTGuide.Localize("ntg.description.lung_damage"), 
            causes = {NTGuide.Localize("ntg.causes.lung_damage")},
            effects = {NTGuide.Localize("ntg.effects.lung_damage")},
            treatments = {NTGuide.Localize("ntg.effects.lung_damage")},  
        },
        Pneumothorax = {
            id = "pneumothorax", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.pneumothorax"), 
            description = NTGuide.Localize("ntg.description.pneumothorax"), 
            causes = {NTGuide.Localize("ntg.causes.pneumothorax")},
            effects = {NTGuide.Localize("ntg.effects.pneumothorax")},
            treatments = {NTGuide.Localize("ntg.treatments.pneumothorax")},  
            firstaid = {NTGuide.Localize("ntg.firstaid.pneumothorax")}, 
        },
        Hyperventilation = {
            id = "hyperventilation", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.hyperventilation"), 
            description = NTGuide.Localize("ntg.description.hyperventilation"), 
            causes = {NTGuide.Localize("ntg.causes.hyperventilation")},
            effects = {NTGuide.Localize("ntg.effects.hyperventilation")},
            treatments = {NTGuide.Localize("ntg.treatments.hyperventilation")},  
        },
        Hypoventilation = {
            id = "hypoventilation", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.hypoventilation"), 
            description = NTGuide.Localize("ntg.description.hypoventilation"), 
            causes = {NTGuide.Localize("ntg.causes.hypoventilation")},
            effects = {NTGuide.Localize("ntg.effects.hypoventilation")},
            treatments = {NTGuide.Localize("ntg.treatments.hypoventilation")},  
        },
        OxygenLow = {
            id = "oxygen_low", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.oxygen_low"), 
            description = NTGuide.Localize("ntg.description.oxygen_low"), 
            causes = {NTGuide.Localize("ntg.causes.oxygen_low")},
            effects = {NTGuide.Localize("ntg.effects.oxygen_low")},
            treatments = {NTGuide.Localize("ntg.treatments.oxygen_low")},  
        },
    },

    -- Heart Afflictions
    Afflictions_Heart = {
        CardiacArrest = {
            id = "cardiac_arrest", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.cardiac_arrest"), 
            description = NTGuide.Localize("ntg.description.cardiac_arrest"), 
            causes = {NTGuide.Localize("ntg.causes.cardiac_arrest")},
            effects = {NTGuide.Localize("ntg.effects.oxygen_low")},
            treatments = {NTGuide.Localize("ntg.treatments.cardiac_arrest")},  
        },
        CardiacTamponade = {
            id = "cardiac_tamponade", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.cardiac_tamponade"), 
            description = NTGuide.Localize("ntg.description.cardiac_tamponade"), 
            causes = {NTGuide.Localize("ntg.causes.cardiac_tamponade")},
            effects = {NTGuide.Localize("ntg.effects.cardiac_tamponade")},
            treatments = {NTGuide.Localize("ntg.treatments.cardiac_tamponade")},
            firstaid = {NTGuide.Localize("ntg.firstaid.cardiac_tamponade")},    
        },
        HeartAttack = {
            id = "heart_attack", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.heart_attack"), 
            description = NTGuide.Localize("ntg.description.heart_attack"), 
            causes = {NTGuide.Localize("ntg.causes.heart_attack")},
            effects = {NTGuide.Localize("ntg.effects.heart_attack")},
            treatments = {NTGuide.Localize("ntg.treatments.heart_attack")},  
        },
        HeartDamage = {
            id = "heart_damage", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.heart_damage"), 
            description = NTGuide.Localize("ntg.description.heart_damage"), 
            causes = {NTGuide.Localize("ntg.causes.heart_damage")},
            effects = {NTGuide.Localize("ntg.effects.heart_damage")},
            treatments = {NTGuide.Localize("ntg.treatments.heart_damage")},  
        },
        IrregularHeartbeat = {
            id = "irregular_heartbeat", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.irregular_heartbeat"), 
            description = NTGuide.Localize("ntg.description.irregular_heartbeat"), 
            causes = {NTGuide.Localize("ntg.causes.irregular_heartbeat")},
            effects = {NTGuide.Localize("ntg.effects.irregular_heartbeat")},
            treatments = {NTGuide.Localize("ntg.treatments.irregular_heartbeat")},  
        },
        Fibrillation = {
            id = "mechanic_fibrillation", 
            category = "mechanics",
            title = NTGuide.Localize("ntg.title.mechanic_fibrillation"), 
            description = NTGuide.Localize("ntg.description.mechanic_fibrillation"), 
            causes = {NTGuide.Localize("ntg.causes.mechanic_fibrillation")},
            effects = {NTGuide.Localize("ntg.effects.mechanic_fibrillation")},
            treatments = {NTGuide.Localize("ntg.treatments.mechanic_fibrillation")},  
        },
    },

    -- Torso Afflictions
    Afflictions_Torso = {
        AorticRupture = {
            id = "aortic_rupture", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.aortic_rupture"), 
            description = NTGuide.Localize("ntg.description.aortic_rupture"), 
            causes = {NTGuide.Localize("ntg.causes.aortic_rupture")},
            effects = {NTGuide.Localize("ntg.effects.aortic_rupture")},
            treatments = {NTGuide.Localize("ntg.treatments.aortic_rupture")},  
            firstaid = {NTGuide.Localize("ntg.firstaid.aortic_rupture")}, 
        },
        InternalBleeding = {
            id = "internal_bleeding", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.internal_bleeding"), 
            description = NTGuide.Localize("ntg.description.internal_bleeding"), 
            causes = {NTGuide.Localize("ntg.causes.internal_bleeding")},
            effects = {NTGuide.Localize("ntg.effects.internal_bleeding")},
            treatments = {NTGuide.Localize("ntg.treatments.internal_bleeding")},  
        },
        RadiationSickness = {
            id = "radiation_sickness", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.radiation_sickness"), 
            description = NTGuide.Localize("ntg.description.radiation_sickness"), 
            causes = {NTGuide.Localize("ntg.causes.radiation_sickness")},
            effects = {NTGuide.Localize("ntg.effects.radiation_sickness")},
            treatments = {NTGuide.Localize("ntg.treatments.radiation_sickness")},  
        },
        KidneyDamage = {
            id = "kidney_damage", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.kidney_damage"), 
            description = NTGuide.Localize("ntg.description.kidney_damage"), 
            causes = {NTGuide.Localize("ntg.causes.kidney_damage")},
            effects = {NTGuide.Localize("ntg.effects.kidney_damage")},
            treatments = {NTGuide.Localize("ntg.treatments.kidney_damage")},  
        },
        LiverDamage = {
            id = "liver_damage", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.liver_damage"), 
            description = NTGuide.Localize("ntg.description.liver_damage"), 
            causes = {NTGuide.Localize("ntg.causes.liver_damage")},
            effects = {NTGuide.Localize("ntg.effects.liver_damage")},
            treatments = {NTGuide.Localize("ntg.treatments.liver_damage")},  
        },
        MorbusinePoisoning = {
            id = "morbusine_poisoning", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.morbusine_poisoning"), 
            description = NTGuide.Localize("ntg.description.morbusine_poisoning"), 
            causes = {NTGuide.Localize("ntg.causes.morbusine_poisoning")},
            effects = {NTGuide.Localize("ntg.effects.morbusine_poisoning")},
            treatments = {NTGuide.Localize("ntg.treatments.morbusine_poisoning")},
            firstaid = {NTGuide.Localize("ntg.firstaid.morbusine_poisoning")},  
        },
        CyanidePoisoning = {
            id = "cyanide_poisoning", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.cyanide_poisoning"), 
            description = NTGuide.Localize("ntg.description.cyanide_poisoning"), 
            causes = {NTGuide.Localize("ntg.causes.cyanide_poisoning")},
            effects = {NTGuide.Localize("ntg.effects.cyanide_poisoning")},
            treatments = {NTGuide.Localize("ntg.treatments.cyanide_poisoning")},  
            firstaid = {NTGuide.Localize("ntg.firstaid.cyanide_poisoning")},
        },
        SufforinPoisoning = {
            id = "sufforin_poisoning", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.sufforin_poisoning"), 
            description = NTGuide.Localize("ntg.description.sufforin_poisoning"), 
            causes = {NTGuide.Localize("ntg.description.sufforin_poisoning")},
            effects = {NTGuide.Localize("ntg.effects.sufforin_poisoning")},
            treatments = {NTGuide.Localize("ntg.treatments.sufforin_poisoning")}, 
            firstaid = {NTGuide.Localize("ntg.firstaid.sufforin_poisoning")}, 
        },
        VanillaOrganDamage = {
            id = "vanilla_organ_damage", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.vanilla_organ_damage"), 
            description = NTGuide.Localize("ntg.description.vanilla_organ_damage"), 
            causes = {NTGuide.Localize("ntg.causes.vanilla_organ_damage")},
            effects = {NTGuide.Localize("ntg.effects.vanilla_organ_damage")},
            treatments = {NTGuide.Localize("ntg.treatments.vanilla_organ_damage")},  
        },
        Analgesia = {
            id = "analgesia", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.analgesia"), 
            description = NTGuide.Localize("ntg.description.analgesia"), 
            causes = {NTGuide.Localize("ntg.causes.analgesia")},
            effects = {NTGuide.Localize("ntg.effects.analgesia")},
            treatments = {NTGuide.Localize("ntg.treatments.analgesia")},  
        },
        Anesthesia = {
            id = "anesthesia", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.anesthesia"), 
            description = NTGuide.Localize("ntg.description.anesthesia"), 
            causes = {NTGuide.Localize("ntg.causes.anesthesia")},
            effects = {NTGuide.Localize("ntg.effects.anesthesia")},
            treatments = {NTGuide.Localize("ntg.treatments.anesthesia")},  
        },
    },

    -- Extremities Afflictions
    Afflictions_Extremities = {
        ArterialBleeding = {
            id = "arterial_bleeding", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.arterial_bleeding"), 
            description = NTGuide.Localize("ntg.description.arterial_bleeding"), 
            causes = {NTGuide.Localize("ntg.causes.arterial_bleeding")},
            effects = {NTGuide.Localize("ntg.effects.arterial_bleeding")},
            treatments = {NTGuide.Localize("ntg.treatments.arterial_bleeding")},
            firstaid = {NTGuide.Localize("ntg.firstaid.arterial_bleeding")},
            seealso = {NTGuide.Localize("ntg.seealso.arterial_bleeding")},  
        },
        TraumaticAmputation = {
            id = "traumatic_amputation", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.traumatic_amputation"), 
            description = NTGuide.Localize("ntg.description.traumatic_amputation"), 
            causes = {NTGuide.Localize("ntg.treatments.traumatic_amputation")},
            effects_traumatic_amputation_ex1 = {NTGuide.Localize("ntg.effects.generaltraumatic_amputation")},
            effects_traumatic_amputation_ex2 = {NTGuide.Localize("ntg.effects.armtraumatic_amputation")},
            effects_traumatic_amputation_ex3 = {NTGuide.Localize("ntg.effects.legtraumatic_amputation")},
            effects_traumatic_amputation_ex4 =  {NTGuide.Localize("ntg.effects.headtraumatic_amputation")},
            treatments = {NTGuide.Localize("ntg.treatments.traumatic_amputation")},  
        },
        SurgicalAmputation = {
            id = "surgical_amputation", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.surgical_amputation"), 
            description = NTGuide.Localize("ntg.description.surgical_amputation"), 
            causes = {NTGuide.Localize("ntg.causes.surgical_amputation")},
            effects_surgical_amputation_ex1 = {NTGuide.Localize("ntg.effects.armsurgical_amputation")},
            effects_surgical_amputation_ex2 = {NTGuide.Localize("ntg.effects.legsurgical_amputation")},
            effects_surgical_amputation_ex3 = {NTGuide.Localize("ntg.effects.headsurgical_amputation")},
            treatments = {NTGuide.Localize("ntg.treatments.surgical_amputation")},  
        },
        Gangrene = {
            id = "gangrene", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.gangrene"), 
            description = NTGuide.Localize("ntg.description.gangrene"), 
            causes = {NTGuide.Localize("ntg.causes.gangrene")},
            effects = {NTGuide.Localize("ntg.effects.gangrene")},
            treatments = {NTGuide.Localize("ntg.treatments.gangrene")},  
        },
        PlasterCast = {
            id = "plaster_cast", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.plaster_cast"), 
            description = NTGuide.Localize("ntg.description.plaster_cast"), 
            causes = {NTGuide.Localize("ntg.causes.plaster_cast")},
            effects = {NTGuide.Localize("ntg.effects.plaster_cast")},  
            treatments = {NTGuide.Localize("ntg.treatments.plaster_cast")},  
        },
        ClampedArteries = {
            id = "clamped_arteries", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.clamped_arteries"), 
            description = NTGuide.Localize("ntg.description.clamped_arteries"), 
            causes = {NTGuide.Localize("ntg.causes.clamped_arteries")},
            effects = {NTGuide.Localize("ntg.effects.clamped_arteries")},  
            treatments = {NTGuide.Localize("ntg.treatments.clamped_arteries")},   
        },
    },

    -- Bone Afflictions
    Afflictions_Bones = {
        BoneDeath = {
            id = "bone_death", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.bone_death"), 
            description = NTGuide.Localize("ntg.description.bone_death"), 
            causes = {NTGuide.Localize("ntg.causes.bone_death")},
            effects = {NTGuide.Localize("ntg.effects.bone_death")},  
            treatments = {NTGuide.Localize("ntg.treatments.bone_death")},    
        },
        BoneDamage = {
            id = "bone_damage", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.bone_damage"), 
            description = NTGuide.Localize("ntg.description.bone_damage"), 
            causes = {NTGuide.Localize("ntg.causes.bone_damage")},
            effects = {NTGuide.Localize("ntg.effects.bone_damage")},  
            treatments = {NTGuide.Localize("ntg.treatments.bone_damage")},    
        },
        Fractures = {
            id = "fractures", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.fractures"), 
            description = NTGuide.Localize("ntg.description.fractures"), 
            causes = {NTGuide.Localize("ntg.causes.fractures")},
            effects_fractures_ex1 = {NTGuide.Localize("ntg.effects.legfractures")},
            effects_fractures_ex2 = {NTGuide.Localize("ntg.effects.armfractures")},
            effects_fractures_ex3 = {NTGuide.Localize("ntg.effects.skullfractures")},
            effects_fractures_ex4 = {NTGuide.Localize("ntg.effects.neckfractures")},
            effects_fractures_ex5 = {NTGuide.Localize("ntg.effects.ribfractures")},
            treatments = {NTGuide.Localize("ntg.treatments.fractures")},
            firstaid = {NTGuide.Localize("ntg.firstaid.fractures")}, 
        },
        Dislocations = {
            id = "dislocations", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.dislocations"), 
            description = NTGuide.Localize("ntg.description.dislocations"), 
            causes = {NTGuide.Localize("ntg.causes.dislocations")},
            effects_dislocations_ex1 = {NTGuide.Localize("ntg.effects.legdislocations")},
            effects_dislocations_ex2 = {NTGuide.Localize("ntg.effects.armdislocations")},
            treatments = {NTGuide.Localize("ntg.treatments.dislocations")},
            firstaid = {NTGuide.Localize("ntg.firstaid.dislocations")},  
        },
    },

    -- 'Any Bodypart' Afflictions
    Afflictions_AnyBodypart = {
        Burns = {
            id = "burns", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.burns"), 
            description = NTGuide.Localize("ntg.description.burns"), 
            causes = {NTGuide.Localize("ntg.causes.burns")},
            effects = {NTGuide.Localize("ntg.effects.burns")},
            treatments = {NTGuide.Localize("ntg.treatments.burns")},  
        },
        OpenWounds = {
            id = "open_wounds", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.open_wounds"), 
            description = NTGuide.Localize("ntg.description.open_wounds"), 
            -- Lacerations
            description_openwounds_ex1 = NTGuide.Localize("ntg.description.open_wounds.lacerations"), 
            causes_openwounds_ex1 = {NTGuide.Localize("ntg.causes.open_wounds.lacerations")},
            effects_openwounds_ex1 = {NTGuide.Localize("ntg.effects.open_wounds.lacerations")},
            treatments_openwounds_ex1 = {NTGuide.Localize("ntg.treatments.open_wounds.lacerations")},
            -- Deep Tissue Injury
            description_openwounds_ex2 = NTGuide.Localize("ntg.description.open_wounds.deeptissueinjury"), 
            causes_openwounds_ex2 = {NTGuide.Localize("ntg.causes.open_wounds.deeptissueinjury")},
            effects_openwounds_ex2 = {NTGuide.Localize("ntg.effects.open_wounds.deeptissueinjury")},
            treatments_openwounds_ex2 = {NTGuide.Localize("ntg.treatments.open_wounds.deeptissueinjury")},
            -- Gunshot Wound
            description_openwounds_ex3 = NTGuide.Localize("ntg.description.open_wounds.gunshotwound"), 
            causes_openwounds_ex3 = {NTGuide.Localize("ntg.causes.open_wounds.gunshotwound")},
            effects_openwounds_ex3 = {NTGuide.Localize("ntg.effects.open_wounds.gunshotwound")},
            treatments_openwounds_ex3 = {NTGuide.Localize("ntg.treatments.open_wounds.gunshotwound")},
            -- Bite Wounds
            description_openwounds_ex4 = NTGuide.Localize("ntg.description.open_wounds.bitewound"), 
            causes_openwounds_ex4 = {NTGuide.Localize("ntg.causes.open_wounds.bitewound")},
            effects_openwounds_ex4 = {NTGuide.Localize("ntg.effects.open_wounds.bitewound")},
            treatments_openwounds_ex4 = {NTGuide.Localize("ntg.treatments.open_wounds.bitewound")},
        },
        InternalWounds = {
            id = "internal_wounds", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.internal_wounds"), 
            description = NTGuide.Localize("ntg.description.internal_wounds"), 
            -- Blunt Force Trauma
            description_internalwounds_ex1 = NTGuide.Localize("ntg.description.internal_wounds.bft"), 
            causes_internalwounds_ex1 = {NTGuide.Localize("ntg.causes.internal_wounds.bft")},
            effects_internalwounds_ex1 = {NTGuide.Localize("ntg.effects.internal_wounds.bft")},
            treatments_internalwounds_ex1 = {NTGuide.Localize("ntg.treatments.internal_wounds.bft")},
            -- Internal Damage
            description_internalwounds_ex2 = NTGuide.Localize("ntg.description.internal_wounds.internaldamage"), 
            causes_internalwounds_ex2 = {NTGuide.Localize("ntg.causes.internal_wounds.internaldamage")},
            effects_internalwounds_ex2 = {NTGuide.Localize("ntg.effects.internal_wounds.internaldamage")},
            treatments_internalwounds_ex2 = {NTGuide.Localize("ntg.treatments.internal_wounds.internaldamage")},
        },
        InfectedWounds = {
            id = "infected_wounds", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.infected_wounds"), 
            description = NTGuide.Localize("ntg.description.infected_wounds"), 
            causes = {NTGuide.Localize("ntg.causes.infected_wounds")},
            effects = {NTGuide.Localize("ntg.effects.infected_wounds")},
            treatments = {NTGuide.Localize("ntg.treatments.infected_wounds")},    
            firstaid = NTGuide.Localize("ntg.firstaid.infected_wounds"), 
        },
        ForeignBodies = {
            id = "foreign_bodies", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.foreign_bodies"), 
            description = NTGuide.Localize("ntg.description.foreign_bodies"), 
            causes = {NTGuide.Localize("ntg.causes.foreign_bodies")},
            effects = {NTGuide.Localize("ntg.effects.foreign_bodies")},
            treatments = {NTGuide.Localize("ntg.treatments.foreign_bodies")},     
        },
        Bleeding = {
            id = "bleeding", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.bleeding"), 
            description = NTGuide.Localize("ntg.description.bleeding"), 
            causes = {NTGuide.Localize("ntg.causes.bleeding")},
            effects = {NTGuide.Localize("ntg.effects.bleeding")},
            treatments = {NTGuide.Localize("ntg.treatments.bleeding")},   
        },
        Ointmented = {
            id = "ointmented", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.ointmented"), 
            description = NTGuide.Localize("ntg.description.ointmented"), 
            causes = {NTGuide.Localize("ntg.causes.ointmented")},
            effects = {NTGuide.Localize("ntg.effects.ointmented")},  
        },
        Chilled = {
            id = "chilled", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.chilled"), 
            description = NTGuide.Localize("ntg.description.ointmented"), 
            causes = {NTGuide.Localize("ntg.causes.chilled")},
            effects = {NTGuide.Localize("ntg.effects.chilled")},    
        },
        Bandaged = {
            id = "bandaged", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.bandaged"), 
            description = NTGuide.Localize("ntg.description.bandaged"), 
            causes = {NTGuide.Localize("ntg.causes.bandaged")},
            effects = {NTGuide.Localize("ntg.effects.bandaged")},
            treatments = {NTGuide.Localize("ntg.treatments.bandaged")},   
        },
        SkinOintmented = {
            id = "skin_ointmented", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.skin_ointmented"), 
            description = NTGuide.Localize("ntg.description.skin_ointmented"), 
            causes = {NTGuide.Localize("ntg.causes.skin_ointmented")},
            effects = {NTGuide.Localize("ntg.effects.skin_ointmented")}, 
        },
    },

    -- Blood Afflictions
    Afflictions_Blood = {
        Hypoxemia = {
            id = "hypoxemia", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.hypoxemia"), 
            description = NTGuide.Localize("ntg.description.hypoxemia"), 
            causes = {NTGuide.Localize("ntg.causes.hypoxemia")},
            effects = {NTGuide.Localize("ntg.effects.hypoxemia")},
            treatments = {NTGuide.Localize("ntg.treatments.hypoxemia")},  
        },
        Sepsis = {
            id = "sepsis", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.sepsis"), 
            description = NTGuide.Localize("ntg.description.sepsis"), 
            causes = {NTGuide.Localize("ntg.causes.sepsis")},
            effects = {NTGuide.Localize("ntg.effects.sepsis")},
            treatments = {NTGuide.Localize("ntg.treatments.sepsis")},  
        },
        HemotransfusionShock = {
            id = "hemotransfusion_shock", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.hemotransfusion_shock"), 
            description = NTGuide.Localize("ntg.description.hemotransfusion_shock"), 
            causes = {NTGuide.Localize("ntg.causes.hemotransfusion_shock")},
            effects = {NTGuide.Localize("ntg.effects.hemotransfusion_shock")},
            treatments = {NTGuide.Localize("ntg.treatments.hemotransfusion_shock")}, 
        },
        BloodLoss = {
            id = "blood_loss", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.blood_loss"), 
            description = NTGuide.Localize("ntg.description.blood_loss"), 
            causes = {NTGuide.Localize("ntg.causes.blood_loss")},
            effects = {NTGuide.Localize("ntg.effects.blood_loss")},
            treatments = {NTGuide.Localize("ntg.treatments.blood_loss")},
        },
        Hypotension = {
            id = "hypotension", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.hypotension"), 
            description = NTGuide.Localize("ntg.description.hypotension"), 
            causes = {NTGuide.Localize("ntg.causes.hypotension")},
            effects = {NTGuide.Localize("ntg.effects.hypotension")},
            treatments = {NTGuide.Localize("ntg.treatments.hypotension")},  
        },
        Hypertension = {
            id = "hypertension", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.hypertension"), 
            description = NTGuide.Localize("ntg.description.hypertension"), 
            causes = {NTGuide.Localize("ntg.causes.hypertension")},
            effects = {NTGuide.Localize("ntg.effects.hypertension")},
            treatments = {NTGuide.Localize("ntg.treatments.hypertension")},  
        },
        Acidosis = {
            id = "acidosis", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.acidosis"), 
            description = NTGuide.Localize("ntg.description.acidosis"), 
            causes = {NTGuide.Localize("ntg.causes.acidosis")},
            effects = {NTGuide.Localize("ntg.effects.acidosis")},
            treatments = {NTGuide.Localize("ntg.treatments.acidosis")},  
        },
        Alkalosis = {
            id = "alkalosis", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.alkalosis"), 
            description = NTGuide.Localize("ntg.description.alkalosis"), 
            causes = {NTGuide.Localize("ntg.causes.alkalosis")},
            effects = {NTGuide.Localize("ntg.effects.alkalosis")},
            treatments = {NTGuide.Localize("ntg.treatments.alkalosis")},    
        },
        Immunity = {
            id = "immunity", 
            category = "mechanics",
            title = NTGuide.Localize("ntg.title.immunity"), 
            description = NTGuide.Localize("ntg.description.immunity"), 
            reduction = {NTGuide.Localize("ntg.reduction.immunity")},
            effects = {NTGuide.Localize("ntg.effects.immunity")},  
        },
        OrganRejection = {
            id = "organ_rejection", 
            category = "mechanics",
            title = NTGuide.Localize("ntg.title.organ_rejection"), 
            description = NTGuide.Localize("ntg.description.organ_rejection"), 
            causes = {NTGuide.Localize("ntg.causes.organ_rejection")},
            effects = {NTGuide.Localize("ntg.effects.organ_rejection")},  
            treatments = {NTGuide.Localize("ntg.treatments.organ_rejection")},  
        },
    },

    -- Surgery Afflictions
    Afflictions_Surgery = {
        TraumaticShock = {
            id = "traumatic_shock", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.traumatic_shock"), 
            description = NTGuide.Localize("ntg.description.traumatic_shock"), 
            causes = {NTGuide.Localize("ntg.causes.traumatic_shock")},
            effects = {NTGuide.Localize("ntg.effects.traumatic_shock")},  
            treatments = {NTGuide.Localize("ntg.treatments.traumatic_shock")},
            prevention = {NTGuide.Localize("ntg.prevention.traumatic_shock")},
        },
        SurgeryIncision = {
            id = "surgery_incision", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.surgery_incision"), 
            description = NTGuide.Localize("ntg.description.surgery_incision"), 
            causes = {NTGuide.Localize("ntg.causes.surgery_incision")},
            effects = {NTGuide.Localize("ntg.effects.surgery_incision")},  
            treatments = {NTGuide.Localize("ntg.treatments.surgery_incision")},  
        },
        ClampedBleeding = {
            id = "clamped_bleeding", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.clamped_bleeding"), 
            description = NTGuide.Localize("ntg.description.clamped_bleeding"), 
            causes = {NTGuide.Localize("ntg.causes.clamped_bleeding")},
            effects = {NTGuide.Localize("ntg.effects.clamped_bleeding")},  
            treatments = {NTGuide.Localize("ntg.treatments.clamped_bleeding")},  
        },
        RetractedSkin = {
            id = "retracted_skin", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.retracted_skin"), 
            description = NTGuide.Localize("ntg.description.retracted_skin"), 
            causes = {NTGuide.Localize("ntg.causes.retracted_skin")},
            effects = {NTGuide.Localize("ntg.effects.retracted_skin")},  
            treatments = {NTGuide.Localize("ntg.treatments.retracted_skin")},  
        },
        DrilledBones = {
            id = "drilled_bones", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.drilled_bones"), 
            description = NTGuide.Localize("ntg.description.drilled_bones"), 
            causes = {NTGuide.Localize("ntg.causes.drilled_bones")},
            effects = {NTGuide.Localize("ntg.effects.drilled_bones")},  
            treatments = {NTGuide.Localize("ntg.treatments.drilled_bones")},  
        },
        SawedBones = {
            id = "sawed_bones", 
            category = "afflictions",
            title = NTGuide.Localize("ntg.title.sawed_bones"), 
            description = NTGuide.Localize("ntg.description.sawed_bones"), 
            causes = {NTGuide.Localize("ntg.causes.sawed_bones")},
            effects = {NTGuide.Localize("ntg.effects.sawed_bones")},  
            treatments = {NTGuide.Localize("ntg.treatments.sawed_bones")},  
        },
    },
    
    -- All items, either added or overriden
    Items = {
        Adrenaline = {
            id = "adrenaline", 
            category = "items",
            title = NTGuide.Localize("ntg.title.adrenaline"), 
            description = NTGuide.Localize("ntg.description.adrenaline"), 
            seealso = {NTGuide.Localize("ntg.seealso.adrenaline")}, 
        },
        AlienBlood = {
            id = "alien_blood", 
            category = "items",
            title = NTGuide.Localize("ntg.title.alien_blood"), 
            description = NTGuide.Localize("ntg.description.alien_blood"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.alien_blood")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.alien_blood")},
        },
        Ambubag = {
            id = "ambubag", 
            category = "items",
            title = NTGuide.Localize("ntg.title.ambubag"), 
            description = NTGuide.Localize("ntg.description.ambubag"), 
            effects = {NTGuide.Localize("ntg.effects.ambubag")}, 
        },
        AnalgesicTank = {
            id = "analgesic_tank", 
            category = "items",
            title = NTGuide.Localize("ntg.title.analgesic_tank"), 
            description = NTGuide.Localize("ntg.description.analgesic_tank"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.analgesic_tank")}, 
        },
        Anaparalyzant = {
            id = "anaparalyzant", 
            category = "items",
            title = NTGuide.Localize("ntg.title.anaparalyzant"), 
            description = NTGuide.Localize("ntg.description.anaparalyzant"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.anaparalyzant")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.anaparalyzant")}, 
        },
        AntibioticGlue = {
            id = "antibiotic_glue", 
            category = "items",
            title = NTGuide.Localize("ntg.title.antibiotic_glue"), 
            description = NTGuide.Localize("ntg.description.antibiotic_glue"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.antibiotic_glue")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.antibiotic_glue")},  
        },
        Antiseptic = {
            id = "antiseptic", 
            category = "items",
            title = NTGuide.Localize("ntg.title.antiseptic"), 
            description = NTGuide.Localize("ntg.description.antiseptic"), 
            seealso = {NTGuide.Localize("ntg.seealso.antiseptic")},   
        },
        AntisepticSprayer = {
            id = "antiseptic_sprayer", 
            category = "items",
            title = NTGuide.Localize("ntg.title.antiseptic_sprayer"), 
            description = NTGuide.Localize("ntg.description.antiseptic_sprayer"), 
            seealso = {NTGuide.Localize("ntg.seealso.antiseptic_sprayer")},  
        },
        ArmItem = {
            id = "arm_item", 
            category = "items",
            title = NTGuide.Localize("ntg.title.arm_item"), 
            description = NTGuide.Localize("ntg.description.arm_item"), 
            seealso = {NTGuide.Localize("ntg.seealso.arm_item")},   
        },
        AED = {
            id = "aed", 
            category = "items",
            title = NTGuide.Localize("ntg.title.aed"), 
            description = NTGuide.Localize("ntg.description.aed"), 
            seealso = {NTGuide.Localize("ntg.seealso.aed")},  
        },
        AutoPulse = {
            id = "autopulse", 
            category = "items",
            title = NTGuide.Localize("ntg.title.autopulse"), 
            description = NTGuide.Localize("ntg.description.autopulse"), 
            seealso = {NTGuide.Localize("ntg.seealso.autopulse")},  
        },
        Azathioprine = {
            id = "azathioprine", 
            category = "items",
            title = NTGuide.Localize("ntg.title.azathioprine"), 
            description = NTGuide.Localize("ntg.description.azathioprine"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.azathioprine")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.azathioprine")},
        },
        Bandages = {
            id = "bandages", 
            category = "items",
            title = NTGuide.Localize("ntg.title.bandages"), 
            description = NTGuide.Localize("ntg.description.bandages"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.bandages")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.bandages")},
            seealso = {NTGuide.Localize("ntg.seealso.bandages")},   
        },
        BloodPacks = {
            id = "blood_packs", 
            category = "items",
            title = NTGuide.Localize("ntg.title.blood_packs"), 
            description = NTGuide.Localize("ntg.description.blood_packs"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.blood_packs")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.blood_packs")},
            seealso = {NTGuide.Localize("ntg.seealso.blood_packs")},   
        },
        BlueShark = {
            id = "blue_shark", 
            category = "items",
            title = NTGuide.Localize("ntg.title.blue_shark"), 
            description = NTGuide.Localize("ntg.description.blue_shark"),   
        },
        BodyBag = {
            id = "body_bag", 
            category = "items",
            title = NTGuide.Localize("ntg.title.body_bag"), 
            description = NTGuide.Localize("ntg.description.body_bag"), 
            seealso = {NTGuide.Localize("ntg.seealso.body_bag")},  
        },
        BrainTransplant = {
            id = "brain_transplant", 
            category = "items",
            title = NTGuide.Localize("ntg.title.brain_transplant"), 
            description = NTGuide.Localize("ntg.description.brain_transplant"), 
            seealso = {NTGuide.Localize("ntg.seealso.brain_transplant")},  
        },
        ABX = {
            id = "abx", 
            category = "items",
            title = NTGuide.Localize("ntg.title.abx"), 
            description = NTGuide.Localize("ntg.description.abx"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.abx")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.abx")},  
        },
        CombatStimulant = {
            id = "combat_stimulant", 
            category = "items",
            title = NTGuide.Localize("ntg.title.combat_stimulant"), 
            description = NTGuide.Localize("ntg.description.combat_stimulant"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.combat_stimulant")},
        },
        Deusizine = {
            id = "deusizine", 
            category = "items",
            title = NTGuide.Localize("ntg.title.deusizine"), 
            description = NTGuide.Localize("ntg.description.deusizine"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.deusizine")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.deusizine")},  
        },
        DialysisFilter = {
            id = "dialysis_filter", 
            category = "items",
            title = NTGuide.Localize("ntg.title.dialysis_filter"), 
            description = NTGuide.Localize("ntg.description.dialysis_filter"), 
            seealso = {NTGuide.Localize("ntg.seealso.dialysis_filter")},  
        },
        DivingKnife = {
            id = "diving_knife", 
            category = "items",
            title = NTGuide.Localize("ntg.title.diving_knife"), 
            description = NTGuide.Localize("ntg.description.diving_knife"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.diving_knife")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.diving_knife")},  
        },
        Drainage = {
            id = "drainage", 
            category = "items",
            title = NTGuide.Localize("ntg.title.drainage"), 
            description = NTGuide.Localize("ntg.description.drainage"), 
            seealso = {NTGuide.Localize("ntg.seealso.drainage")},  
        },
        EmptyBloodPack = {
            id = "empty_blood_pack", 
            category = "items",
            title = NTGuide.Localize("ntg.title.empty_blood_pack"), 
            description = NTGuide.Localize("ntg.description.empty_blood_pack"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.empty_blood_pack")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.empty_blood_pack")},
            seealso = {NTGuide.Localize("ntg.seealso.empty_blood_pack")},   
        },
        EndovascularBalloon = {
            id = "endovascular_balloon", 
            category = "items",
            title = NTGuide.Localize("ntg.title.endovascular_balloon"), 
            description = NTGuide.Localize("ntg.description.endovascular_balloon"), 
            seealso = {NTGuide.Localize("ntg.seealso.endovascular_balloon")},    
        },
        Fentanyl = {
            id = "fentanyl", 
            category = "items",
            title = NTGuide.Localize("ntg.title.fentanyl"), 
            description = NTGuide.Localize("ntg.description.fentanyl"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.fentanyl")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.fentanyl")},  
        },
        GelIcePack = {
            id = "gel_ice_pack", 
            category = "items",
            title = NTGuide.Localize("ntg.title.gel_ice_pack"), 
            description = NTGuide.Localize("ntg.description.gel_ice_pack"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.gel_ice_pack")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.gel_ice_pack")},  
        },
        Gypsum = {
            id = "gypsum", 
            category = "items",
            title = NTGuide.Localize("ntg.title.gypsum"), 
            description = NTGuide.Localize("ntg.description.gypsum"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.gypsum")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.gypsum")},
            seealso = {NTGuide.Localize("ntg.seealso.gypsum")},   
        },
        Haloperidol = {
            id = "haloperidol", 
            category = "items",
            title = NTGuide.Localize("ntg.title.haloperidol"), 
            description = NTGuide.Localize("ntg.description.haloperidol"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.haloperidol")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.haloperidol")},  
        },
        HealthScanner = {
            id = "health_scanner", 
            category = "items",
            title = NTGuide.Localize("ntg.title.health_scanner"), 
            description = NTGuide.Localize("ntg.description.health_scanner"), 
            seealso = {NTGuide.Localize("ntg.seealso.health_scanner")},  
        },
        HematologyAnalyzer = {
            id = "hematology_analyzer", 
            category = "items",
            title = NTGuide.Localize("ntg.title.hematology_analyzer"), 
            description = NTGuide.Localize("ntg.description.hematology_analyzer"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.hematology_analyzer")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.hematology_analyzer")},
            seealso = {NTGuide.Localize("ntg.seealso.hematology_analyzer")},  
        },
        Hemostat = {
            id = "hemostat", 
            category = "items",
            title = NTGuide.Localize("ntg.title.hemostat"), 
            description = NTGuide.Localize("ntg.description.hemostat"), 
            seealso = {NTGuide.Localize("ntg.seealso.hemostat")}, 
        },
        Hyperzine = {
            id = "hyperzine", 
            category = "items",
            title = NTGuide.Localize("ntg.title.hyperzine"), 
            description = NTGuide.Localize("ntg.description.hyperzine"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.hyperzine")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.hyperzine")},  
        },
        HeartTransplant = {
            id = "heart_transplant", 
            category = "items",
            title = NTGuide.Localize("ntg.title.heart_transplant"), 
            description = NTGuide.Localize("ntg.description.heart_transplant"), 
            seealso = {NTGuide.Localize("ntg.seealso.heart_transplant")}, 
        },
        KidneyTransplant = {
            id = "kidney_transplant", 
            category = "items",
            title = NTGuide.Localize("ntg.title.kidney_transplant"), 
            description = NTGuide.Localize("ntg.description.kidney_transplant"), 
            seealso = {NTGuide.Localize("ntg.seealso.kidney_transplant")},  
        },
        LegItem = {
            id = "leg_item", 
            category = "items",
            title = NTGuide.Localize("ntg.title.leg_item"), 
            description = NTGuide.Localize("ntg.description.leg_item"), 
            seealso = {NTGuide.Localize("ntg.seealso.leg_item")},  
        },
        LiverTransplant = {
            id = "liver_transplant", 
            category = "items",
            title = NTGuide.Localize("ntg.title.liver_transplant"), 
            description = NTGuide.Localize("ntg.description.liver_transplant"), 
            seealso = {NTGuide.Localize("ntg.seealso.liver_transplant")},  
        },
        LiquidOxygenite = {
            id = "liquid_oxygenite", 
            category = "items",
            title = NTGuide.Localize("ntg.title.liquid_oxygenite"), 
            description = NTGuide.Localize("ntg.description.liquid_oxygenite"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.liquid_oxygenite")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.liquid_oxygenite")},  
        },
        LungTransplant = {
            id = "lung_transplant", 
            category = "items",
            title = NTGuide.Localize("ntg.title.lung_transplant"), 
            description = NTGuide.Localize("ntg.description.lung_transplant"), 
            seealso = {NTGuide.Localize("ntg.seealso.lung_transplant")},  
        },
        Mannitol = {
            id = "mannitol", 
            category = "items",
            title = NTGuide.Localize("ntg.title.mannitol"), 
            description = NTGuide.Localize("ntg.description.mannitol"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.mannitol")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.mannitol")},   
        },
        ManualDefibrillator = {
            id = "manual_defibrillator", 
            category = "items",
            title = NTGuide.Localize("ntg.title.manual_defibrillator"), 
            description = NTGuide.Localize("ntg.description.manual_defibrillator"), 
            seealso = {NTGuide.Localize("ntg.seealso.manual_defibrillator")},  
        },
        MedicalStent = {
            id = "medical_stent", 
            category = "items",
            title = NTGuide.Localize("ntg.title.medical_stent"), 
            description = NTGuide.Localize("ntg.description.medical_stent"), 
            seealso = {NTGuide.Localize("ntg.seealso.medical_stent")},  
        },
        Methamphetamine = {
            id = "methamphetamine", 
            category = "items",
            title = NTGuide.Localize("ntg.title.methamphetamine"), 
            description = NTGuide.Localize("ntg.description.methamphetamine"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.methamphetamine")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.methamphetamine")},  
        },
        Morphine = {
            id = "morphine", 
            category = "items",
            title = NTGuide.Localize("ntg.title.morphine"), 
            description = NTGuide.Localize("ntg.description.morphine"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.morphine")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.morphine")},  
        },
        Naloxone = {
            id = "naloxone", 
            category = "items",
            title = NTGuide.Localize("ntg.title.naloxone"), 
            description = NTGuide.Localize("ntg.description.naloxone"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.naloxone")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.naloxone")},  
        },
        Needle = {
            id = "needle", 
            category = "items",
            title = NTGuide.Localize("ntg.title.needle"), 
            description = NTGuide.Localize("ntg.description.needle"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.needle")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.needle")},  
        },
        Nitroglycerin = {
            id = "nitroglycerin", 
            category = "items",
            title = NTGuide.Localize("ntg.title.nitroglycerin"), 
            description = NTGuide.Localize("ntg.description.nitroglycerin"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.nitroglycerin")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.nitroglycerin")},
            seealso = {NTGuide.Localize("ntg.seealso.nitroglycerin")},  
        },
        Opium = {
            id = "opium", 
            category = "items",
            title = NTGuide.Localize("ntg.title.opium"), 
            description = NTGuide.Localize("ntg.description.opium"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.opium")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.opium")},  
        },
        MultipurposeScalpel = {
            id = "multipurpose_scalpel", 
            category = "items",
            title = NTGuide.Localize("ntg.title.multipurpose_scalpel"), 
            description = NTGuide.Localize("ntg.description.multipurpose_scalpel"), 
            description_multipurposescalpel_ex1 = {NTGuide.Localize("ntg.description.multipurpose_scalpel_ex1")},
            description_multipurposescalpel_ex2 = {NTGuide.Localize("ntg.description.multipurpose_scalpel_ex2")},
            description_multipurposescalpel_ex3 = {NTGuide.Localize("ntg.description.multipurpose_scalpel_ex3")},
        },
        OsteosynthesisImplants = {
            id = "osteosynthesis_implants", 
            category = "items",
            title = NTGuide.Localize("ntg.title.osteosynthesis_implants"), 
            description = NTGuide.Localize("ntg.description.osteosynthesis_implants"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.osteosynthesis_implants")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.osteosynthesis_implants")},  
        },
        Plastiseal = {
            id = "plastiseal", 
            category = "items",
            title = NTGuide.Localize("ntg.title.plastiseal"), 
            description = NTGuide.Localize("ntg.description.plastiseal"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.plastiseal")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.plastiseal")},
            seealso = {NTGuide.Localize("ntg.seealso.plastiseal")},  
        },
        Propofol = {
            id = "propofol", 
            category = "items",
            title = NTGuide.Localize("ntg.title.propofol"), 
            description = NTGuide.Localize("ntg.description.propofol"), 
            sideeffects = {NTGuide.Localize("ntg.sideeffects.propofol")},
            seealso = {NTGuide.Localize("ntg.seealso.propofol")},  
        },
        RaptorBaneExtract = {
            id = "raptor_bane_extract", 
            category = "items",
            title = NTGuide.Localize("ntg.title.raptor_bane_extract"), 
            description = NTGuide.Localize("ntg.description.raptor_bane_extract"), 
            seealso = {NTGuide.Localize("ntg.seealso.raptor_bane_extract")},  
        },
        RefrigeratedContainer = {
            id = "refrigerated_container", 
            category = "items",
            title = NTGuide.Localize("ntg.title.refrigerated_container"), 
            description = NTGuide.Localize("ntg.description.refrigerated_container"), 
            seealso = {NTGuide.Localize("ntg.seealso.refrigerated_container")},  
        },
        RefrigeratedCrate = {
            id = "refrigerated_crate", 
            category = "items",
            title = NTGuide.Localize("ntg.title.refrigerated_crate"), 
            description = NTGuide.Localize("ntg.description.refrigerated_crate"), 
            seealso = {NTGuide.Localize("ntg.seealso.refrigerated_crate")},  
        },
        RingersSolution = {
            id = "ringers_solution", 
            category = "items",
            title = NTGuide.Localize("ntg.title.ringers_solution"), 
            description = NTGuide.Localize("ntg.description.ringers_solution"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.ringers_solution")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.ringers_solution")},  
        },
        Saline = {
            id = "saline", 
            category = "items",
            title = NTGuide.Localize("ntg.title.saline"), 
            description = NTGuide.Localize("ntg.description.saline"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.saline")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.saline")},  
        },
        Scalpel = {
            id = "scalpel", 
            category = "items",
            title = NTGuide.Localize("ntg.title.scalpel"), 
            description = NTGuide.Localize("ntg.description.scalpel"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.scalpel")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.scalpel")},
            seealso = {NTGuide.Localize("ntg.seealso.scalpel")},  
        },
        SkinRetractors = {
            id = "skin_retractors", 
            category = "items",
            title = NTGuide.Localize("ntg.title.skin_retractors"), 
            description = NTGuide.Localize("ntg.description.skin_retractors"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.skin_retractors")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.skin_retractors")},  
        },
        SodiumNitroprusside = {
            id = "sodium_nitroprusside", 
            category = "items",
            title = NTGuide.Localize("ntg.title.sodium_nitroprusside"), 
            description = NTGuide.Localize("ntg.description.sodium_nitroprusside"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.sodium_nitroprusside")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.sodium_nitroprusside")},
            seealso = {NTGuide.Localize("ntg.seealso.sodium_nitroprusside")},  
        },
        SpinalCordImplants = {
            id = "spinal_cord_implants", 
            category = "items",
            title = NTGuide.Localize("ntg.title.spinal_cord_implants"), 
            description = NTGuide.Localize("ntg.description.spinal_cord_implants"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.spinal_cord_implants")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.spinal_cord_implants")},  
        },
        StasisBag = {
            id = "stasis_bag", 
            category = "items",
            title = NTGuide.Localize("ntg.title.stasis_bag"), 
            description = NTGuide.Localize("ntg.description.stasis_bag"), 
            effects = {NTGuide.Localize("ntg.effects.stasis_bag")},  
        },
        Streptokinase = {
            id = "streptokinase", 
            category = "items",
            title = NTGuide.Localize("ntg.title.streptokinase"), 
            description = NTGuide.Localize("ntg.description.streptokinase"), 
            effects = {NTGuide.Localize("ntg.effects.streptokinase")},
            seealso = {NTGuide.Localize("ntg.seealso.streptokinase")},  
        },
        SurgeryTable = {
            id = "surgery_table", 
            category = "items",
            title = NTGuide.Localize("ntg.title.surgery_table"), 
            description = NTGuide.Localize("ntg.description.surgery_table"), 
            seealso = {NTGuide.Localize("ntg.seealso.surgery_table")}, 
        },
        SurgicalDrill = {
            id = "surgical_drill", 
            category = "items",
            title = NTGuide.Localize("ntg.title.surgical_drill"), 
            description = NTGuide.Localize("ntg.description.surgical_drill"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.surgical_drill")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.surgical_drill")},
            seealso = {NTGuide.Localize("ntg.seealso.surgical_drill")},   
        },
        SurgicalSaw = {
            id = "surgical_saw", 
            category = "items",
            title = NTGuide.Localize("ntg.title.surgical_saw"), 
            description = NTGuide.Localize("ntg.description.surgical_saw"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.surgical_saw")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.surgical_saw")},
            seealso = {NTGuide.Localize("ntg.seealso.surgical_saw")},  
        },
        Sutures = {
            id = "sutures", 
            category = "items",
            title = NTGuide.Localize("ntg.title.sutures"), 
            description = NTGuide.Localize("ntg.description.sutures"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.sutures")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.sutures")},  
        },
        Thiamine = {
            id = "thiamine", 
            category = "items",
            title = NTGuide.Localize("ntg.title.thiamine"), 
            description = NTGuide.Localize("ntg.description.thiamine"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.thiamine")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.thiamine")},  
        },
        Tourniquet = {
            id = "tourniquet", 
            category = "items",
            title = NTGuide.Localize("ntg.title.tourniquet"), 
            description = NTGuide.Localize("ntg.description.tourniquet"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.tourniquet")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.tourniquet")},
            seealso = {NTGuide.Localize("ntg.seealso.tourniquet")},  
        },
        ToxinFilter = {
            id = "toxin_filter", 
            category = "items",
            title = NTGuide.Localize("ntg.title.toxin_filter"), 
            description = NTGuide.Localize("ntg.description.toxin_filter"), 
            treatments_toxinfilter_ex1 = {NTGuide.Localize("ntg.treatments.toxin_filter.morbusine")},
            treatments_toxinfilter_ex2 = {NTGuide.Localize("ntg.treatments.toxin_filter.cyanide")},
            treatments_toxinfilter_ex3 = {NTGuide.Localize("ntg.treatments.toxin_filter.sufforin")},
            treatments_toxinfilter_ex4 = {NTGuide.Localize("ntg.treatments.toxin_filter.deliriumine")},  
        },
        TraumaShears = {
            id = "trauma_shears", 
            category = "items",
            title = NTGuide.Localize("ntg.title.trauma_shears"), 
            description = NTGuide.Localize("ntg.description.trauma_shears"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.trauma_shears")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.trauma_shears")},  
        },
        Tweezers = {
            id = "tweezers", 
            category = "items",
            title = NTGuide.Localize("ntg.title.tweezers"), 
            description = NTGuide.Localize("ntg.description.tweezers"), 
            effects = {NTGuide.Localize("ntg.effects.tweezers")},
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.tweezers")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.tweezers")},
            seealso = {NTGuide.Localize("ntg.seealso.tweezers")},  
        },
        Wrench = {
            id = "wrench", 
            category = "items",
            title = NTGuide.Localize("ntg.title.wrench"), 
            description = NTGuide.Localize("ntg.description.wrench"), 
            applicationsuccess = {NTGuide.Localize("ntg.applicationsuccess.wrench")},
            applicationfailed = {NTGuide.Localize("ntg.applicationfailed.wrench")},  
        },
    },

    -- Procedures category. 
    SurgicalProcedures = {
        OpenCloseSurgery = {
            id = "open_close_surgery", 
            category = "procedures",
            title = NTGuide.Localize("ntg.title.open_close_surgery"), 
            description = NTGuide.Localize("ntg.description.open_close_surgery"), 
            steps = {NTGuide.Localize("ntg.steps.open_close_surgery")},  
        },
        OsteosynthesisSurgery = {
            id = "osteosynthesis_surgery", 
            category = "procedures",
            title = NTGuide.Localize("ntg.title.osteosynthesis_surgery"), 
            description = NTGuide.Localize("ntg.description.osteosynthesis_surgery"), 
            steps = {NTGuide.Localize("ntg.steps.osteosynthesis_surgery")},  
        },
        AorticRuptureSurgery = {
            id = "aortic_rupture_surgery", 
            category = "procedures",
            title = NTGuide.Localize("ntg.title.aortic_rupture_surgery"), 
            description = NTGuide.Localize("ntg.description.aortic_rupture_surgery"), 
            steps = {NTGuide.Localize("ntg.steps.aortic_rupture_surgery")},  
        },
        AmputationSurgery = {
            id = "amputation_surgery", 
            category = "procedures",
            title = NTGuide.Localize("ntg.title.amputation_surgery"), 
            description = NTGuide.Localize("ntg.description.amputation_surgery"), 
            steps = {NTGuide.Localize("ntg.steps.amputation_surgery")},  
        },
        OrganTransplantSurgery = {
            id = "organ_transplant_surgery", 
            category = "procedures",
            title = NTGuide.Localize("ntg.title.organ_transplant_surgery"), 
            description = NTGuide.Localize("ntg.description.organ_transplant_surgery"), 
            steps = {NTGuide.Localize("ntg.steps.organ_transplant_surgery")},  
        },
    },

    -- Information category
    Information = {
    },
}